version: '3.7'
services:
  wireguard:
    image: linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris 
      - SERVERPORT=51820 
      - PEERS=2
      - PEERDNS=auto 
      - ALLOWEDIPS=0.0.0.0/0 #
      - INTERNAL_SUBNET=10.13.13.0/24 
     volumes:
      - /opt/wireguard-server/config:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
